# Hadolint configuration
# https://github.com/hadolint/hadolint
# Purpose: Ensures Docker best practices while allowing flexibility for development environments

# Ignore specific rules that are too strict for our development use case
# These rules are important for production but can be overly restrictive during development
ignore:
  # Use specific tags instead of latest (DL3006)
  # Reason: Development images often use 'latest' for convenience and faster iteration
  - DL3006

  # Use specific digest instead of tag (DL3008)
  # Reason: Tags are more readable and manageable in development
  - DL3008

  # Pin versions in apt-get install (DL3009)
  # Reason: Development environments benefit from latest package versions
  - DL3009

  # Use --no-cache flag with apk (DL3018)
  # Reason: Development images often need caching for faster builds
  - DL3018

  # Use apk add --no-cache (DL3019)
  # Reason: Development images often need caching for faster builds
  - DL3019

  # Pin versions in pip install (DL3013)
  # Reason: Development environments benefit from latest package versions
  - DL3013

  # Use --no-cache-dir flag with pip (DL3059)
  # Reason: Development images often need caching for faster builds
  - DL3059
