# Markdownlint configuration
# https://github.com/DavidAnson/markdownlint
# Purpose: Ensures consistent Markdown formatting while allowing flexibility for documentation

# Line length configuration (MD013)
# Purpose: Set reasonable line length limits while allowing flexibility for different content types
MD013:
  line_length: 88  # Match Python line length for consistency
  code_blocks: false  # Allow long lines in code blocks (often necessary)
  tables: false  # Allow long lines in tables (data presentation)
  headings: false  # Allow long headings (sometimes necessary for clarity)

# First line heading (MD041)
# Purpose: Allow files without headings at the start (common in README files)
MD041: false  # Don't require first line to be a heading

# First line H1 (MD025)
# Purpose: Allow files without H1 headings (some files don't need main headings)
MD025: false  # Don't require H1 at the start of files

# Multiple H1 (MD003)
# Purpose: Allow multiple H1 headings (some documents have multiple main sections)
MD003: false  # Allow multiple H1 headings

# Inline HTML (MD033)
# Purpose: Allow inline HTML when necessary for formatting
MD033: false  # Allow inline HTML (sometimes needed for complex formatting)

# Emphasis used instead of heading (MD036)
# Purpose: Allow emphasis in lists and other contexts
MD036: false  # Allow emphasis in lists and other contexts

# No trailing punctuation (MD026)
# Purpose: Allow headings with punctuation (common in technical documentation)
MD026: false  # Allow headings with punctuation

# List item indentation (MD007)
# Purpose: Enforce consistent list indentation
MD007:
  indent: 2  # Use 2 spaces for list indentation (consistent with YAML)

# List marker style (MD004)
# Purpose: Enforce consistent list marker style
MD004:
  style: dash  # Use dashes for unordered lists (consistent with YAML)

# Unordered list indentation (MD030)
# Purpose: Enforce consistent spacing around list markers
MD030:
  ul_single: 2  # 2 spaces after dash for single-line lists
  ol_single: 2  # 2 spaces after number for single-line lists
  ul_multi: 2  # 2 spaces after dash for multi-line lists
  ol_multi: 2  # 2 spaces after number for multi-line lists

# Hard tabs (MD010)
# Purpose: Allow tabs in code blocks where they might be necessary
MD010:
  spaces_per_tab: 2  # Convert tabs to 2 spaces

# Trailing spaces (MD009)
# Purpose: Allow trailing spaces for line breaks in Markdown
MD009:
  br_spaces: 2  # Allow 2 trailing spaces for line breaks (Markdown standard)

# No blank lines around fenced code blocks (MD031)
# Purpose: Allow flexibility around code blocks
MD031: false  # Don't require blank lines around code blocks

# Fenced code blocks should have language (MD040)
# Purpose: Allow code blocks without language specification
MD040: false  # Don't require language specification for code blocks

# No bare URLs (MD034)
# Purpose: Allow bare URLs in documentation (common and useful)
MD034: false  # Allow bare URLs in documentation

# No space in emphasis (MD037)
# Purpose: Allow spaces in emphasis for readability
MD037: false  # Allow spaces in emphasis

# No space in links (MD039)
# Purpose: Allow spaces in links for readability
MD039: false  # Allow spaces in links

# No space in code (MD038)
# Purpose: Allow spaces in code spans for readability
MD038: false  # Allow spaces in code spans
