# CI-specific Docker Compose overrides
# Optimized for build speed over runtime performance

services:
  discord:
    build:
      context: "."
      dockerfile: "services/discord/Dockerfile"
      cache_from:
        - type=gha,scope=services
        - ghcr.io/gabrielpreston/python-audio:latest
        - ghcr.io/gabrielpreston/discord:latest
      args:
        BUILDKIT_INLINE_CACHE: "1"
    image: "ghcr.io/gabrielpreston/discord:latest"
    # Disable unnecessary ports in CI
    ports: []
    # Use minimal environment for CI
    env_file:
      - "./.env.ci"
    environment:
      - PYTHONPATH=/app
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    # Disable restart policy in CI
    restart: "no"
    # Use minimal logging
    logging:
      driver: "none"

  stt:
    build:
      context: "."
      dockerfile: "services/stt/Dockerfile"
      cache_from:
        - type=gha,scope=services
        - ghcr.io/gabrielpreston/python-ml:latest
        - ghcr.io/gabrielpreston/stt:latest
      args:
        BUILDKIT_INLINE_CACHE: "1"
    image: "ghcr.io/gabrielpreston/stt:latest"
    ports: []
    env_file:
      - "./.env.ci"
    environment:
      - PYTHONPATH=/app
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    restart: "no"
    logging:
      driver: "none"


  orchestrator:
    build:
      context: "."
      dockerfile: "services/orchestrator/Dockerfile"
      cache_from:
        - type=gha,scope=services
        - ghcr.io/gabrielpreston/python-ml:latest
        - ghcr.io/gabrielpreston/orchestrator:latest
      args:
        BUILDKIT_INLINE_CACHE: "1"
    image: "ghcr.io/gabrielpreston/orchestrator:latest"
    ports: []
    env_file:
      - "./.env.ci"
    environment:
      - PYTHONPATH=/app
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    restart: "no"
    logging:
      driver: "none"


  # Add missing services for complete CI coverage
  flan:
    build:
      context: "."
      dockerfile: "services/flan/Dockerfile"
      cache_from:
        - type=gha,scope=services
        - ghcr.io/gabrielpreston/python-ml:latest
        - ghcr.io/gabrielpreston/flan:latest
      args:
        BUILDKIT_INLINE_CACHE: "1"
    image: "ghcr.io/gabrielpreston/flan:latest"
    ports: []
    env_file:
      - "./.env.ci"
    environment:
      - PYTHONPATH=/app
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - FW_MODEL=tiny  # Use tiny model for faster CI
    restart: "no"
    logging:
      driver: "none"

  bark:
    build:
      context: "."
      dockerfile: "services/bark/Dockerfile"
      cache_from:
        - type=gha,scope=services
        - ghcr.io/gabrielpreston/python-ml:latest
        - ghcr.io/gabrielpreston/bark:latest
      args:
        BUILDKIT_INLINE_CACHE: "1"
    image: "ghcr.io/gabrielpreston/bark:latest"
    ports: []
    env_file:
      - "./.env.ci"
    environment:
      - PYTHONPATH=/app
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - BARK_USE_SMALL_MODELS=true  # Use small models for faster CI
    restart: "no"
    logging:
      driver: "none"

  audio:
    build:
      context: "."
      dockerfile: "services/audio/Dockerfile"
      cache_from:
        - type=gha,scope=services
        - ghcr.io/gabrielpreston/python-ml:latest
        - ghcr.io/gabrielpreston/audio:latest
      args:
        BUILDKIT_INLINE_CACHE: "1"
    image: "ghcr.io/gabrielpreston/audio:latest"
    ports: []
    env_file:
      - "./.env.ci"
    environment:
      - PYTHONPATH=/app
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    restart: "no"
    logging:
      driver: "none"

  guardrails:
    build:
      context: "."
      dockerfile: "services/guardrails/Dockerfile"
      cache_from:
        - type=gha,scope=services
        - ghcr.io/gabrielpreston/python-ml:latest
        - ghcr.io/gabrielpreston/guardrails:latest
      args:
        BUILDKIT_INLINE_CACHE: "1"
    image: "ghcr.io/gabrielpreston/guardrails:latest"
    ports: []
    env_file:
      - "./.env.ci"
    environment:
      - PYTHONPATH=/app
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    restart: "no"
    logging:
      driver: "none"

  testing:
    build:
      context: "."
      dockerfile: "services/testing/Dockerfile"
      cache_from:
        - type=gha,scope=services
        - ghcr.io/gabrielpreston/python-ml:latest
        - ghcr.io/gabrielpreston/testing:latest
      args:
        BUILDKIT_INLINE_CACHE: "1"
    image: "ghcr.io/gabrielpreston/testing:latest"
    ports: []
    env_file:
      - "./.env.ci"
    environment:
      - PYTHONPATH=/app
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    restart: "no"
    logging:
      driver: "none"

  monitoring:
    build:
      context: "."
      dockerfile: "services/monitoring/Dockerfile"
      cache_from:
        - type=gha,scope=services
        - ghcr.io/gabrielpreston/python-ml:latest
        - ghcr.io/gabrielpreston/monitoring:latest
      args:
        BUILDKIT_INLINE_CACHE: "1"
    image: "ghcr.io/gabrielpreston/monitoring:latest"
    ports: []
    env_file:
      - "./.env.ci"
    environment:
      - PYTHONPATH=/app
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    restart: "no"
    logging:
      driver: "none"
