# CI-specific Docker Compose overrides
# Optimized for build speed over runtime performance
version: "3.8"

services:
  discord:
    build:
      context: "."
      dockerfile: "services/discord/Dockerfile"
      cache_from:
        - type=gha,scope=services
        - ghcr.io/gabrielpreston/python-audio:latest
        - ghcr.io/gabrielpreston/discord:latest
      args:
        BUILDKIT_INLINE_CACHE: "1"
    image: "ghcr.io/gabrielpreston/discord:latest"
    # Disable unnecessary ports in CI
    ports: []
    # Use minimal environment for CI
    env_file:
      - "./.env.ci"
    environment:
      - PYTHONPATH=/app
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    # Disable restart policy in CI
    restart: "no"
    # Use minimal logging
    logging:
      driver: "none"
    # CI-specific health checks for faster startup detection
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "/app/scripts/health_check.py",
          "http://localhost:8001/health/ready",
          "--timeout",
          "3",
          "--ci",
        ]
      interval: 3s
      timeout: 2s
      retries: 3
      start_period: 15s

  stt:
    build:
      context: "."
      dockerfile: "services/stt/Dockerfile"
      cache_from:
        - type=gha,scope=services
        - ghcr.io/gabrielpreston/python-ml:latest
        - ghcr.io/gabrielpreston/stt:latest
      args:
        BUILDKIT_INLINE_CACHE: "1"
    image: "ghcr.io/gabrielpreston/stt:latest"
    ports: []
    env_file:
      - "./.env.ci"
    environment:
      - PYTHONPATH=/app
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    restart: "no"
    logging:
      driver: "none"
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "/app/scripts/health_check.py",
          "http://localhost:9000/health/ready",
          "--timeout",
          "3",
          "--ci",
        ]
      interval: 3s
      timeout: 2s
      retries: 3
      start_period: 15s

  llm:
    build:
      context: "."
      dockerfile: "services/llm/Dockerfile"
      cache_from:
        - type=gha,scope=services
        - ghcr.io/gabrielpreston/python-ml:latest
        - ghcr.io/gabrielpreston/llm:latest
      args:
        BUILDKIT_INLINE_CACHE: "1"
    image: "ghcr.io/gabrielpreston/llm:latest"
    ports: []
    env_file:
      - "./.env.ci"
    environment:
      - PYTHONPATH=/app
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    restart: "no"
    logging:
      driver: "none"
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "/app/scripts/health_check.py",
          "http://localhost:8000/health/ready",
          "--timeout",
          "3",
          "--ci",
        ]
      interval: 3s
      timeout: 2s
      retries: 3
      start_period: 15s

  orchestrator:
    build:
      context: "."
      dockerfile: "services/orchestrator/Dockerfile"
      cache_from:
        - type=gha,scope=services
        - ghcr.io/gabrielpreston/python-ml:latest
        - ghcr.io/gabrielpreston/orchestrator:latest
      args:
        BUILDKIT_INLINE_CACHE: "1"
    image: "ghcr.io/gabrielpreston/orchestrator:latest"
    ports: []
    env_file:
      - "./.env.ci"
    environment:
      - PYTHONPATH=/app
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    restart: "no"
    logging:
      driver: "none"
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "/app/scripts/health_check.py",
          "http://localhost:8200/health/ready",
          "--timeout",
          "3",
          "--ci",
        ]
      interval: 3s
      timeout: 2s
      retries: 3
      start_period: 15s

  tts:
    build:
      context: "."
      dockerfile: "services/tts/Dockerfile"
      cache_from:
        - type=gha,scope=services
        - ghcr.io/gabrielpreston/python-ml:latest
        - ghcr.io/gabrielpreston/tts:latest
      args:
        BUILDKIT_INLINE_CACHE: "1"
    image: "ghcr.io/gabrielpreston/tts:latest"
    ports: []
    env_file:
      - "./.env.ci"
    environment:
      - PYTHONPATH=/app
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    restart: "no"
    logging:
      driver: "none"
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "/app/scripts/health_check.py",
          "http://localhost:7000/health/ready",
          "--timeout",
          "3",
          "--ci",
        ]
      interval: 3s
      timeout: 2s
      retries: 3
      start_period: 15s

  # Add missing services for complete CI coverage
  flan:
    build:
      context: "."
      dockerfile: "services/llm_flan/Dockerfile"
      cache_from:
        - type=gha,scope=services
        - ghcr.io/gabrielpreston/python-ml:latest
        - ghcr.io/gabrielpreston/flan:latest
      args:
        BUILDKIT_INLINE_CACHE: "1"
    image: "ghcr.io/gabrielpreston/flan:latest"
    ports: []
    env_file:
      - "./.env.ci"
    environment:
      - PYTHONPATH=/app
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - FW_MODEL=tiny  # Use tiny model for faster CI
    restart: "no"
    logging:
      driver: "none"
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "/app/scripts/health_check.py",
          "http://localhost:8100/health/ready",
          "--timeout",
          "3",
          "--ci",
        ]
      interval: 3s
      timeout: 2s
      retries: 3
      start_period: 15s

  bark:
    build:
      context: "."
      dockerfile: "services/bark/Dockerfile"
      cache_from:
        - type=gha,scope=services
        - ghcr.io/gabrielpreston/python-ml:latest
        - ghcr.io/gabrielpreston/bark:latest
      args:
        BUILDKIT_INLINE_CACHE: "1"
    image: "ghcr.io/gabrielpreston/bark:latest"
    ports: []
    env_file:
      - "./.env.ci"
    environment:
      - PYTHONPATH=/app
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - BARK_USE_SMALL_MODELS=true  # Use small models for faster CI
    restart: "no"
    logging:
      driver: "none"
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "/app/scripts/health_check.py",
          "http://localhost:7100/health/ready",
          "--timeout",
          "3",
          "--ci",
        ]
      interval: 3s
      timeout: 2s
      retries: 3
      start_period: 15s

  audio:
    build:
      context: "."
      dockerfile: "services/audio/Dockerfile"
      cache_from:
        - type=gha,scope=services
        - ghcr.io/gabrielpreston/python-ml:latest
        - ghcr.io/gabrielpreston/audio:latest
      args:
        BUILDKIT_INLINE_CACHE: "1"
    image: "ghcr.io/gabrielpreston/audio:latest"
    ports: []
    env_file:
      - "./.env.ci"
    environment:
      - PYTHONPATH=/app
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    restart: "no"
    logging:
      driver: "none"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9100/health/ready"]
      interval: 3s
      timeout: 2s
      retries: 3
      start_period: 10s

  guardrails:
    build:
      context: "."
      dockerfile: "services/guardrails/Dockerfile"
      cache_from:
        - type=gha,scope=services
        - ghcr.io/gabrielpreston/python-ml:latest
        - ghcr.io/gabrielpreston/guardrails:latest
      args:
        BUILDKIT_INLINE_CACHE: "1"
    image: "ghcr.io/gabrielpreston/guardrails:latest"
    ports: []
    env_file:
      - "./.env.ci"
    environment:
      - PYTHONPATH=/app
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    restart: "no"
    logging:
      driver: "none"
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "/app/scripts/health_check.py",
          "http://localhost:9300/health/ready",
          "--timeout",
          "3",
          "--ci",
        ]
      interval: 3s
      timeout: 2s
      retries: 3
      start_period: 15s

  testing:
    build:
      context: "."
      dockerfile: "services/testing/Dockerfile"
      cache_from:
        - type=gha,scope=services
        - ghcr.io/gabrielpreston/python-ml:latest
        - ghcr.io/gabrielpreston/testing:latest
      args:
        BUILDKIT_INLINE_CACHE: "1"
    image: "ghcr.io/gabrielpreston/testing:latest"
    ports: []
    env_file:
      - "./.env.ci"
    environment:
      - PYTHONPATH=/app
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    restart: "no"
    logging:
      driver: "none"
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "/app/scripts/health_check.py",
          "http://localhost:8080/health/ready",
          "--timeout",
          "3",
          "--ci",
        ]
      interval: 3s
      timeout: 2s
      retries: 3
      start_period: 10s

  monitoring:
    build:
      context: "."
      dockerfile: "services/monitoring/Dockerfile"
      cache_from:
        - type=gha,scope=services
        - ghcr.io/gabrielpreston/python-ml:latest
        - ghcr.io/gabrielpreston/monitoring:latest
      args:
        BUILDKIT_INLINE_CACHE: "1"
    image: "ghcr.io/gabrielpreston/monitoring:latest"
    ports: []
    env_file:
      - "./.env.ci"
    environment:
      - PYTHONPATH=/app
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    restart: "no"
    logging:
      driver: "none"
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "/app/scripts/health_check.py",
          "http://localhost:9090/health/ready",
          "--timeout",
          "3",
          "--ci",
        ]
      interval: 3s
      timeout: 2s
      retries: 3
      start_period: 10s
