[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 88
target-version = ['py311']
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 88
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
skip_glob = ["**/.venv/**", "**/build/**", "**/dist/**"]

[tool.ruff]
target-version = "py311"
line-length = 88

[tool.ruff.lint]
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "I",   # isort
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "UP",  # pyupgrade
    "N",   # pep8-naming
    "S",   # flake8-bandit
    "RET", # flake8-return
    "SIM", # flake8-simplify
]
ignore = [
    "E501",  # line too long, handled by black
    "B008",  # do not perform function calls in argument defaults
    "C901",  # too complex
    "B904",  # within an except clause, raise exceptions with raise ... from err
    "UP038", # use X | Y in isinstance call instead of (X, Y)
    "S101",  # use of assert (common in tests)
    "S104",  # hardcoded bind all interfaces (common in Docker)
    "S603",  # subprocess call (common in Docker)
    "S607",  # starting a process with a partial executable path
    "RET504", # unnecessary assignment before return
    "RET505", # unnecessary else after return
    "SIM108", # use ternary operator (sometimes less readable)
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]  # unused imports in __init__.py

[tool.ruff.lint.isort]
known-first-party = ["services"]

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
follow_imports = "skip"
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true
strict_equality = true
disallow_any_generics = true
disallow_any_unimported = true
disallow_any_expr = false  # Too strict for practical use

[[tool.mypy.overrides]]
module = [
    "discord.*",
    "faster_whisper.*",
    "openai.*",
    "pydantic.*",
    "fastapi.*",
    "uvicorn.*",
    "httpx.*",
    "structlog.*",
    "numpy.*",
    "soundfile.*",
    "librosa.*",
    "webrtcvad.*",
    "rapidfuzz.*",
    "openwakeword.*",
    "piper.*",
    "prometheus_client.*",
    "mcp.*",
    "pytest.*",
    "freezegun.*",
    "llama_cpp.*",
    "starlette.*",
]
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = [
    "services.tests.*",
    "services.*.tests.*",
    "services.*.conftest",
    "services.tests.conftest",
    "services.tests.mocks.*",
    "services.common.test_config",
    "services.common.config_examples",
    "services.common.tests.*",
    "services.orchestrator.tests.*",
    "services.common.tests.conftest",
    "services.orchestrator.tests.conftest",
    "services.tests.conftest",
    "services.tests.mocks.discord_client",
]
# Only test files and examples get lenient treatment
disallow_untyped_defs = false
disallow_incomplete_defs = false
disallow_untyped_decorators = false
warn_return_any = false
warn_no_return = false
warn_unreachable = false
strict_equality = false

