blank_issues_enabled: false
contact_links:
  - name: CI troubleshooting guide
    url: https://github.com/gabrielpreston/discord-voice-lab/actions
    about: Review recent GitHub Actions runs and download artifacts before filing an issue.
