# Audio Processing Configuration
# This file contains application-specific configuration for the audio-processor service

audio_processing:
  enhancement:
    model_path: "/app/models/metricgan-plus"
    device: "cpu"
    enable_high_pass: true
    cutoff_frequency: 80.0
    enable_metricgan: true
    model_source: "speechbrain/metricgan-plus-voicebank"
    model_savedir: "pretrained_models/metricgan-plus"

  performance:
    max_concurrent_requests: 10
    frame_processing_timeout_ms: 20 # Industry standard for real-time
    enhancement_timeout_ms: 50
    buffer_size_ms: 20
    chunk_size_ms: 20
    buffer_size_chunks: 5
    connection_pool_size: 5
    request_timeout: 30.0

  quality:
    min_snr_db: 20.0
    target_sample_rate: 16000
    target_channels: 1
    enable_volume_normalization: true
    enable_noise_reduction: true
    silence_threshold: 0.01
    silence_duration: 2.0

  wake_detection:
    enabled: true
    phrases: ["hey assistant", "ok assistant", "computer"]
    confidence_threshold: 0.8
    sample_rate: 16000
    frame_duration_ms: 30
    aggressiveness: 1

  processing:
    max_segment_duration: 30.0
    min_segment_duration: 0.5
    enable_audio_enhancement: true
    enable_volume_normalization: true
    enable_noise_reduction: true
    enable_wake_detection: true
