# Workflow: Build Base Images
# Purpose: Build shared base images weekly and on base Dockerfile changes
name: 'Build Base Images'
description: |
  Build shared base images for Docker optimization
on:
  schedule:
    - cron: '0 2 * * 0'  # Weekly on Sunday at 2 AM
  push:
    paths:
      - 'services/base/**'
      - 'requirements-base.txt'
      - 'requirements-dev.txt'
      - 'requirements-test.txt'
  workflow_dispatch: {}
permissions:
  contents: 'read'
  packages: 'write'  # Required for GHCR publishing

concurrency:
  group: 'base-images'
  cancel-in-progress: true

env:
  PIP_DISABLE_PIP_VERSION_CHECK: '1'
  PIP_NO_PYTHON_VERSION_WARNING: '1'
  PYTHONDONTWRITEBYTECODE: '1'

jobs:
  build-base-images:
    name: 'Build Base Images'
    runs-on: 'ubuntu-latest'
    timeout-minutes: 45
    env:
      ACTIONS_CACHE_SERVICE_V2: true
    steps:
      - name: 'Checkout repository'
        uses: 'actions/checkout@v4.2.2'

      - name: 'Set up Docker Buildx'
        uses: 'docker/setup-buildx-action@v3'
        with:
          driver-opts: |
            image=moby/buildkit:latest

      - name: 'Build and push Python Base Image'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: services/base/Dockerfile.python-base
          tags: ghcr.io/${{ github.repository_owner }}/python-base:latest
          cache-from: type=gha,scope=base-images
          cache-to: type=gha,mode=max,scope=base-images
          push: true
          load: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Build and push Python Audio Base Image'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: services/base/Dockerfile.python-audio
          build-args: BASE_IMAGE=discord-voice-lab/python-base:latest
          tags: ghcr.io/${{ github.repository_owner }}/python-audio:latest
          cache-from: type=gha,scope=base-images
          cache-to: type=gha,mode=max,scope=base-images
          push: true
          load: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Build and push Python ML Base Image'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: services/base/Dockerfile.python-ml
          build-args: BASE_IMAGE=discord-voice-lab/python-base:latest
          tags: ghcr.io/${{ github.repository_owner }}/python-ml:latest
          cache-from: type=gha,scope=base-images
          cache-to: type=gha,mode=max,scope=base-images
          push: true
          load: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Build and push Tools Base Image'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: services/base/Dockerfile.tools
          build-args: BASE_IMAGE=discord-voice-lab/python-base:latest
          tags: ghcr.io/${{ github.repository_owner }}/tools:latest
          cache-from: type=gha,scope=base-images
          cache-to: type=gha,mode=max,scope=base-images
          push: true
          load: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Build and push MCP Toolchain Base Image'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: services/base/Dockerfile.mcp-toolchain
          build-args: BASE_IMAGE=discord-voice-lab/python-base:latest
          tags: ghcr.io/${{ github.repository_owner }}/mcp-toolchain:latest
          cache-from: type=gha,scope=base-images
          cache-to: type=gha,mode=max,scope=base-images
          push: true
          load: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Build Summary'
        run: |
          echo "## Base Images Built Successfully" >> $GITHUB_STEP_SUMMARY
          echo "| Image | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|-------|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| python-base | ✅ Built |" >> $GITHUB_STEP_SUMMARY
          echo "| python-audio | ✅ Built |" >> $GITHUB_STEP_SUMMARY
          echo "| python-ml | ✅ Built |" >> $GITHUB_STEP_SUMMARY
          echo "| tools | ✅ Built |" >> $GITHUB_STEP_SUMMARY
          echo "| mcp-toolchain | ✅ Built |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Base images are now available for use in CI builds." >> $GITHUB_STEP_SUMMARY
