# Workflow: Build Base Images
# Purpose: Build shared base images weekly and on base Dockerfile changes
name: "Build Base Images"
on:
  schedule:
    - cron: "0 2 * * 0" # Weekly on Sunday at 2 AM
  push:
    paths:
      - "services/base/**"
      - "requirements-base.txt"
      - "requirements-dev.txt"
      - "requirements-test.txt"
  workflow_dispatch: {}
permissions:
  contents: "read"
  packages: "write" # Required for GHCR publishing

concurrency:
  group: "base-images"
  cancel-in-progress: true

env:
  PIP_DISABLE_PIP_VERSION_CHECK: "1"
  PIP_NO_PYTHON_VERSION_WARNING: "1"
  PYTHONDONTWRITEBYTECODE: "1"

jobs:
  build-base-images:
    name: "Build Base Images"
    runs-on: "ubuntu-latest"
    timeout-minutes: 45
    env:
      ACTIONS_CACHE_SERVICE_V2: true
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v4.2.2"
      - name: "Setup job context"
        uses: actions/github-script@v7
        with:
          script: |
            console.log('Job started:', context.job)
            console.log('Repository:', context.repo.full_name)
            console.log('Ref:', context.ref)
            console.log('Workflow:', context.workflow)
            console.log('Run ID:', context.runId)

      - name: "Set up Docker Buildx"
        uses: "docker/setup-buildx-action@v3"
        with:
          driver-opts: |
            image=moby/buildkit:latest

      - name: "Log in to GitHub Container Registry"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Build and push Python Base Image with retry"
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 15
          max_attempts: 3
          command: |
            docker buildx build \
              --file services/base/Dockerfile.python-base \
              --tag ghcr.io/${{ github.repository_owner }}/python-base:latest \
              --cache-from type=gha,scope=base-images \
              --cache-to type=gha,mode=max,scope=base-images \
              --load . && \
            docker push ghcr.io/${{ github.repository_owner }}/python-base:latest

      - name: "Build and push Python Audio Base Image with retry"
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 15
          max_attempts: 3
          command: |
            docker buildx build \
              --file services/base/Dockerfile.python-audio \
              --build-arg BASE_IMAGE=ghcr.io/${{ github.repository_owner }}/python-base:latest \
              --tag ghcr.io/${{ github.repository_owner }}/python-audio:latest \
              --cache-from type=gha,scope=base-images \
              --cache-to type=gha,mode=max,scope=base-images \
              --load . && \
            docker push ghcr.io/${{ github.repository_owner }}/python-audio:latest

      - name: "Build and push Python ML Base Image with retry"
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 15
          max_attempts: 3
          command: |
            docker buildx build \
              --file services/base/Dockerfile.python-ml \
              --build-arg BASE_IMAGE=ghcr.io/${{ github.repository_owner }}/python-base:latest \
              --tag ghcr.io/${{ github.repository_owner }}/python-ml:latest \
              --cache-from type=gha,scope=base-images \
              --cache-to type=gha,mode=max,scope=base-images \
              --load . && \
            docker push ghcr.io/${{ github.repository_owner }}/python-ml:latest

      - name: "Build and push Tools Base Image with retry"
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 15
          max_attempts: 3
          command: |
            docker buildx build \
              --file services/base/Dockerfile.tools \
              --build-arg BASE_IMAGE=ghcr.io/${{ github.repository_owner }}/python-base:latest \
              --tag ghcr.io/${{ github.repository_owner }}/tools:latest \
              --cache-from type=gha,scope=base-images \
              --cache-to type=gha,mode=max,scope=base-images \
              --load . && \
            docker push ghcr.io/${{ github.repository_owner }}/tools:latest

      - name: "Build and push MCP Toolchain Base Image with retry"
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 15
          max_attempts: 3
          command: |
            docker buildx build \
              --file services/base/Dockerfile.mcp-toolchain \
              --build-arg BASE_IMAGE=ghcr.io/${{ github.repository_owner }}/python-base:latest \
              --tag ghcr.io/${{ github.repository_owner }}/mcp-toolchain:latest \
              --cache-from type=gha,scope=base-images \
              --cache-to type=gha,mode=max,scope=base-images \
              --load . && \
            docker push ghcr.io/${{ github.repository_owner }}/mcp-toolchain:latest

      - name: "Build and push Python ML Audio Base Image with retry"
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 15
          max_attempts: 3
          command: |
            docker buildx build \
              --file services/base/Dockerfile.python-ml-audio \
              --build-arg BASE_IMAGE=ghcr.io/${{ github.repository_owner }}/python-ml:latest \
              --tag ghcr.io/${{ github.repository_owner }}/python-ml-audio:latest \
              --cache-from type=gha,scope=base-images \
              --cache-to type=gha,mode=max,scope=base-images \
              --load . && \
            docker push ghcr.io/${{ github.repository_owner }}/python-ml-audio:latest

      - name: "Build and push Python ML Compiled Base Image with retry"
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 15
          max_attempts: 3
          command: |
            docker buildx build \
              --file services/base/Dockerfile.python-ml-compiled \
              --build-arg BASE_IMAGE=ghcr.io/${{ github.repository_owner }}/python-ml:latest \
              --tag ghcr.io/${{ github.repository_owner }}/python-ml-compiled:latest \
              --cache-from type=gha,scope=base-images \
              --cache-to type=gha,mode=max,scope=base-images \
              --load . && \
            docker push ghcr.io/${{ github.repository_owner }}/python-ml-compiled:latest

      - name: "Build and push Python ML Torch Base Image with retry"
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 15
          max_attempts: 3
          command: |
            docker buildx build \
              --file services/base/Dockerfile.python-ml-torch \
              --build-arg BASE_IMAGE=ghcr.io/${{ github.repository_owner }}/python-ml:latest \
              --tag ghcr.io/${{ github.repository_owner }}/python-ml-torch:latest \
              --cache-from type=gha,scope=base-images \
              --cache-to type=gha,mode=max,scope=base-images \
              --load . && \
            docker push ghcr.io/${{ github.repository_owner }}/python-ml-torch:latest

      - name: "Build and push Python ML Transformers Base Image with retry"
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 15
          max_attempts: 3
          command: |
            docker buildx build \
              --file services/base/Dockerfile.python-ml-transformers \
              --build-arg BASE_IMAGE=ghcr.io/${{ github.repository_owner }}/python-ml:latest \
              --tag ghcr.io/${{ github.repository_owner }}/python-ml-transformers:latest \
              --cache-from type=gha,scope=base-images \
              --cache-to type=gha,mode=max,scope=base-images \
              --load . && \
            docker push ghcr.io/${{ github.repository_owner }}/python-ml-transformers:latest

      - name: "Build Summary"
        run: |
          echo "## Base Images Built Successfully" >> $GITHUB_STEP_SUMMARY
          echo "| Image | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|-------|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| python-base | ✅ Built |" >> $GITHUB_STEP_SUMMARY
          echo "| python-audio | ✅ Built |" >> $GITHUB_STEP_SUMMARY
          echo "| python-ml | ✅ Built |" >> $GITHUB_STEP_SUMMARY
          echo "| python-ml-audio | ✅ Built |" >> $GITHUB_STEP_SUMMARY
          echo "| python-ml-compiled | ✅ Built |" >> $GITHUB_STEP_SUMMARY
          echo "| python-ml-torch | ✅ Built |" >> $GITHUB_STEP_SUMMARY
          echo "| python-ml-transformers | ✅ Built |" >> $GITHUB_STEP_SUMMARY
          echo "| tools | ✅ Built |" >> $GITHUB_STEP_SUMMARY
          echo "| mcp-toolchain | ✅ Built |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Base images are now available for use in CI builds." >> $GITHUB_STEP_SUMMARY
      - name: "Cleanup resources with reporting"
        if: always()
        run: |
          echo "::group::Resource Cleanup Report"

          # Capture before cleanup
          before_space=$(df -h / | awk 'NR==2{print $4}')
          before_images=$(docker images -q | wc -l)

          # Cleanup operations
          echo "Cleaning Docker system..."
          docker system prune -f --volumes

          echo "Cleaning build cache..."
          docker builder prune -f

          # Capture after cleanup
          after_space=$(df -h / | awk 'NR==2{print $4}')
          after_images=$(docker images -q | wc -l)

          echo "Cleanup Results:"
          echo "  Disk space: $before_space to $after_space"
          echo "  Images removed: $((before_images - after_images))"
          echo "::endgroup::"
      - name: "Job Status Summary"
        if: always()
        run: |
          echo "::group::Job Status Summary"
          echo "Job: ${{ github.job }}"
          echo "Runner: ${{ runner.os }} (${{ runner.arch }})"
          echo "Available Space: $(df -h / | awk 'NR==2{print $4}')"
          echo "Docker Images: $(docker images -q | wc -l)"
          echo "Cache: GitHub Actions Cache v2 enabled"
          echo "Retry: Native GitHub Actions retry (3 attempts, 15min timeout)"
          echo "::endgroup::"
