# Workflow: Security CI
# Purpose: Security scanning workflow
name: "Security CI"
on:
  workflow_call: {}

permissions:
  contents: "read"

jobs:
  security-scan:
    name: "Security Scan"
    runs-on: "ubuntu-latest"
    environment: "discord-voice-lab"
    timeout-minutes: 15
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v4.2.2"
      - name: "Run security scan"
        run: make security
